# Generated by Django 5.2.3 on 2025-07-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('Passion', models.CharField(max_length=30)),
            ],
        ),
    ]
