# Generated by Django 5.2.3 on 2025-07-31 02:40

import myweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_resumemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='resume',
            field=models.FileField(upload_to='Resume', validators=[myweb.models.validate_pdf]),
        ),
    ]
