# Generated by Django 5.2.3 on 2025-07-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_alter_resumemodel_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='skill')),
            ],
        ),
    ]
