# Generated by Django 5.2.3 on 2025-07-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='projects_photo')),
                ('title', models.CharField(max_length=30)),
                ('live_link', models.URLField()),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.filter')),
            ],
        ),
    ]
