# Generated by Django 5.2.3 on 2025-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_projectmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
