# Generated by Django 5.2.3 on 2025-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_alter_projectmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
